### PR TITLE
Extend ROM by Aggregation function - SUM

### PR DESCRIPTION
**Pull request by gotar**
for exmple:

```
  ROM.env.relation(:users).sum(:age) # => 20
```

Return number (similar to count) not relation as other functions.

### CODE REVIEW

**Comment by gotar** [comment]
@solnic any thoughts about it? I can add other aggregation functions too (min, max, avg)

**Comment by solnic** [comment]
can you rebase this?

**Comment by gotar** [comment]
rebased

**Comment by jamesmoriarty** [comment]
:+1:

**Comment by solnic** [comment]
thanks @gotar :+1: for adding all aggregation functions from sequel, feel free to just push it to master

**Pull request merged**
