### PR TITLE
Add full_text_search plugin for postgresql

### PR DESCRIPTION
**Pull request by ianks**
This PR adds a `pg_full_text_search` plugin which enables usage of [Sequel's `full_text_search`](https://sequel.jeremyevans.net/rdoc-adapters/classes/Sequel/Postgres/DatasetMethods.html#method-i-full_text_search) functionality.

It is a simple wrapper, and keeps the original Sequel API, and wraps the dataset in a relation.

### CODE REVIEW

**Comment by ianks** [comment]
[Here's the link to the CI check for convienience](https://github.com/ianks/rom-sql/commit/b830b6f16ce620aa1167c20dd47a40b2500198fe/checks?check_suite_id=398240013)

**Comment by solnic** [comment]
Thanks! Could you rebase this so that there's no b830b6f16ce620aa1167c20dd47a40b2500198fe here?

**Comment by ianks** [comment]
Ok so everything has been squashed and conflicts resolved. Can we get this merged?

**Comment by solnic** [comment]
@ianks thanks, it's merged 😄 I also gave you access so pls use this repo instead of the fork for any future PRs <3

**Pull request merged**
