### PR TITLE
Use optional types for inferred schema

### PR DESCRIPTION
**Pull request by jodosha**
Closes https://github.com/rom-rb/rom-sql/issues/88

### CODE REVIEW

**Comment by solnic** [comment]
We do use `optional` types [here](https://github.com/rom-rb/rom-sql/blob/master/lib/rom/sql/schema/inferrer.rb#L54). This doesn't work for you?

**Comment by jodosha** [comment]
@solnic @flash-gordon There are several cases that a `Strict` type won't fit:

  * `Date`, `DateTime`, and `Time` are often represented as strings in the database. Strict types expect as input the exact type they represent. So `ROM::Sql::Types::Date[Date.today.to_s]` raises an error. We should be more flexible.

  * Similarly `Decimal` blows up if we pass a float: `ROM::Sql::Types::Decimal[3.14]`.

  * The actual behavior is: when we use `NOT NULL` constraint, we get a `Strict` type. If we have `users.active boolean NOT NULL default false`, when we omit the input (`active`): `repository.create(name: 'Luca')` we'll get an error from ROM/dry-types (`Message: <"nil (NilClass) has invalid type for :active">`). Shall we let the database to handle this case?

**Comment by flash-gordon** [comment]
I guess we fixed all the issues we've got so far, so this can be closed. However, there is a bunch of type specs in the PR, @solnic what do you think about them?

**Comment by flash-gordon** [comment]
I guess we fixed all the issues we've got so far, so this can be closed. However, there is a bunch of type specs in the PR, @solnic what do you think about them?

**Comment by jodosha** [comment]
Closing in favor of the already merged https://github.com/rom-rb/rom-sql/pull/101 👍

**Pull request closed without merging**
