### PR TITLE
Add migration_options to be able to use the default rake migration tasks with custom opts.

### PR DESCRIPTION
**Pull request by wuarmin**
Hey,
I want to use the default rake migration tasks, but need to customize the table opt. This PR would fix my need.

thanks and best regards

### CODE REVIEW

**Comment by wuarmin** [comment]
Hi @solnic,
why wasn't this PR merged into the main branch?
thanks!

**Comment by flash-gordon** [comment]
@wuarmin why was it sent to release-3.5, though?

**Comment by wuarmin** [comment]
@flash-gordon I found the reason: https://github.com/rom-rb/rom-sql/pull/406#issuecomment-1067661665. I forgot that. Will this ft land in main-branch?

**Comment by solnic** [comment]
@wuarmin yes it will

**Pull request merged**
