### PR TITLE
Update to work with decoupled alias options

### PR DESCRIPTION
**Pull request by solnic**
Refs rom-rb/rom#512

### CODE REVIEW

**Comment by solnic** [comment]
Seems like just one spec is failing:

```
Failures:

  1) ROM::SQL::Schema::PostgresInferrer inferring db-specific attributes can infer attributes for dataset
     Failure/Error: expect(schema[name]).to eql(attribute)
     
       expected: #<ROM::SQL::Attribute[id] name=:id db_type="uuid" database="postgres" primary_key=true source=ROM::Relation::Name(test_inferrence) alias=nil>
            got: #<ROM::SQL::Attribute[String] name=:id db_type="uuid" database="postgres" primary_key=true source=ROM::Relation::Name(test_inferrence) alias=nil>
     
       (compared using eql?)
     
       Diff:
       @@ -1,2 +1,2 @@
       -#<ROM::SQL::Attribute[id] name=:id db_type="uuid" database="postgres" primary_key=true source=ROM::Relation::Name(test_inferrence) alias=nil>
       +#<ROM::SQL::Attribute[String] name=:id db_type="uuid" database="postgres" primary_key=true source=ROM::Relation::Name(test_inferrence) alias=nil>
       
     # ./spec/integration/schema/inferrer/postgres_spec.rb:124:in `block (4 levels) in <top (required)>'
     # ./spec/integration/schema/inferrer/postgres_spec.rb:123:in `each'
     # ./spec/integration/schema/inferrer/postgres_spec.rb:123:in `block (3 levels) in <top (required)>'

Finished in 0.17484 seconds (files took 0.519 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/integration/schema/inferrer/postgres_spec.rb:122 # ROM::SQL::Schema::PostgresInferrer inferring db-specific attributes can infer attributes for dataset

Randomized with seed 6891
```

@waiting-for-dev would you be able to look into this?

**Comment by waiting-for-dev** [comment]
Sure @solnic . Surely it is because I haven't the same database environment that is expected by the test suite, and I had 8 localized test failures which were attributable to it :sweat_smile: It seems one of them is masking a "true" error. A good addition would be to make the expected environment reproducible to ease collaborations. If I find the time I could add Docker files just as in `rom` repository.

By the way, maybe you could give me push permissions for this branch?

**Comment by flash-gordon** [comment]
I'll fix this

**Comment by flash-gordon** [comment]
done, @solnic feel free to merge anytime

**Pull request merged**
