### PR TITLE
Create migration files in auto-migrations

### PR DESCRIPTION
**Pull request by flash-gordon**
- [x] Create table
- [x] Alter table
- [x] Test various options for tables/indexes/FKs

### CODE REVIEW

**Comment by flash-gordon** [comment]
@solnic the most difficult part so far is naming 😥

**Comment by solnic** [comment]
@flash-gordon naming what? :) Don't cry 🤗

**Comment by flash-gordon** [comment]
specifically those runner/inline_runner/writer/whatever. Naming them with verbs would be easier

**Comment by solnic** [comment]
So name them with verbs :) WDYT about using template files instead of generating stuff by concatenating strings?

**Comment by flash-gordon** [comment]
@solnic I wouldn't bother at this point, this stuff takes ~30 lines and it not going to get any bigger, we'll see though

**Pull request merged**
