### PR TITLE
Add support for the FILTER clause

### PR DESCRIPTION
**Pull request by flash-gordon**
🎉

### CODE REVIEW

**Comment by flash-gordon** [comment]
Say you want to get a number of users who registered less than a day ago, a week ago and a month ago. All this using a single query. With FILTER it's almost trivial

```ruby
users.select {
  [int::count(:id).filter { created_at > time::now() - any::cast('1 day', 'interval') }.as(:last_day_users),
   int::count(:id).filter { created_at > time::now() - any::cast('1 week', 'interval') }.as(:last_week_users),
   int::count(:id).filter { created_at > time::now() - any::cast('1 month', 'interval') }.as(:last_month_users)]
}.order(nil)
```

**Comment by solnic** [comment]
Would be good to move it to a PG-specific extension. WDYT?

**Comment by flash-gordon** [comment]
@solnic technically, it’s a sql’s standard, it’s just only PG supports it right now

**Comment by solnic** [comment]
I see, OK merging in.

**Pull request merged**
