### PR TITLE
Remove ORDER to make COUNT faster

### PR DESCRIPTION
**Pull request by joelvh**
Lifted from `graphql-ruby`: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/pagination/sequel_dataset_connection.rb#L19

### CODE REVIEW

**Comment by flash-gordon** [comment]
I genuinely wonder which DBMS doesn't optimize it itself...

**Comment by solnic** [comment]
@flash-gordon are you saying we should make this optimization on a per-db type basis?

**Comment by flash-gordon** [comment]
@solnic I'm saying that no DB doesn't do it by itself. Actually, using `count` with `order by` won't even work in PG, which means Sequel already ignores the ordering. This PR, however, reveals a bug in `total` because it uses `unlimited` datasets, which is plain wrong. If you want to paginate over a filtered relation, you'll get incorrect results. I'm amazed this hasn't been reported. I'll file an issue.

**Comment by joelvh** [comment]
@flash-gordon nice catch #366

**Pull request closed without merging**
