### PR TITLE
Slowdown a spec even more to avoid flapping tests

### PR DESCRIPTION
**Pull request by splattael**
Let's see...

### CODE REVIEW

**Comment by splattael** [comment]
I don't think slowing down helps here. I have to investigate more...

**Comment by solnic** [comment]
the build was passing consistently for quite a while...maybe the problem is gone...can we close this for now? :)

**Comment by splattael** [comment]
Ups, I've totally forgot to close this one.

This flapping spec has already been fixed in f9bf56a78f184993b725c645a84dfb998082196a

Thanks for the heads-up!

**Comment by solnic** [comment]
no worries :) thanks for taking care of this! :heart:

**Pull request closed without merging**
