### PR TITLE
Fix user documentation link

### PR DESCRIPTION
**Pull request by j-a-m-l**

### CODE REVIEW

**Comment by solnic** [comment]
hey, thanks but I can't merge this in. READMEs are now rendered automatically via workflows, so I need to fix it there.

**Comment by j-a-m-l** [comment]
OK, @solnic. So what could I do for changing it?

**Comment by solnic** [comment]
@j-a-m-l nothing 😄 I just fixed it in devtools

**Comment by j-a-m-l** [comment]
Thank you

**Pull request closed without merging**
