### PR TITLE
Add PG::Array operations

### PR DESCRIPTION
**Pull request by flash-gordon**

### CODE REVIEW

**Comment by solnic** [comment]
Fantastic :) 👍

**Comment by flash-gordon** [comment]
😄

**Comment by flash-gordon** [comment]
@solnic btw there is a problem with docs, there is a clash in method names, i.e. `Attribute<PG::JSONB>` and `Attribute<PG::Array>` both have `contain` and only one gets into the docs. Perhaps I could use `overloaded` for this... will give it a shot tonight

**Comment by solnic** [comment]
@flash-gordon yes you should be able to use `@overload` to fix this

**Comment by flash-gordon** [comment]
@solnic hmm, this works but I have to put all docs in one place, in a giant docstring with macros, that's pretty crazy :) I'll push it later

**Comment by flash-gordon** [comment]
meh, I'm not happy with the result, I'll release it as is and will look into creating a plugin for yard

**Comment by solnic** [comment]
@flash-gordon you could ask [Loren](https://github.com/lsegal) if he has any suggestions

**Comment by flash-gordon** [comment]
@solnic I think what we need here is kind of docs for generics, i.e. list of methods for `ROM::SQL::Attribute<PG::Array>`, `ROM::SQL::Attribute<PG::JSONB>`, etc

**Pull request merged**
