### PR TITLE
Add support for joins by association name

### PR DESCRIPTION
**Pull request by flash-gordon**
Since association carries all info we need for a join it seems reasonable to infer join condition automatically.

### CODE REVIEW

**Comment by flash-gordon** [comment]
It also can be sutin like `join(using: :assoc_name)`

**Comment by solnic** [comment]
We already have `join(another_relation)` which does exactly that

**Comment by flash-gordon** [comment]
Not exactly. You can have two associations with the same relation. And
relation join doesn't work if the association named differently from the
relation. I'll show an example later

**Comment by flash-gordon** [comment]
@solnic I pushed an example https://github.com/rom-rb/rom-sql/pull/171/commits/131e927f27b2eb2eeff7eefc180200eaf7cdbfd0

**Comment by solnic** [comment]
oh I see, this makes sense. I'm not a big fan of using symbols though. I also planned to make relations dumpable to sql literals, which is somewhat related, because we could have `join(users.as(:author))` and use its `alias` to construct required join. I'm OK with supporting plain symbols in this case, but eventually I'd like to support passing aliased relations too. WDYT?

**Comment by flash-gordon** [comment]
interesting, yes, this makes a lot of sense. BTW I don't like symbols either. I'll mark the failing spec as pending

**Pull request merged**
