### PR TITLE
Make inferrer to use non-strict types

### PR DESCRIPTION
**Pull request by flash-gordon**
See https://github.com/rom-rb/rom-sql/issues/88

### CODE REVIEW

**Comment by solnic** [comment]
Could you add a couple of specs that verify that it works, esp when a value can be implicitly coerced by sequel, and when there's `nil` (to make sure `optional` works as expected)?

**Comment by flash-gordon** [comment]
yeah, I was thinking about it. Just not sure what exactly we need to test, there are various cases for missing, `nil`, and uncoerced values mixed with different DB datatypes, implicit coercion policies and `null/not null/default` options.  I'll spend some time investigating Sequel's behavior. Also do you think we need a strict inferrer or not (e.g. as an option)?

**Comment by solnic** [comment]
@flash-gordon at least the basic scenarios like `user_repo.create(name: 'foo', age: nil)` where `age` is an optional. I actually have second thoughts about implicit coercions, since this way we'd start relying on sequel coercion (if it exists, actually) and that's not what I would like to have tbh. In general when a field has a type specified then only this type should be used, so ie if we have a date_time field in the db, then only DateTime objects should be allowed. We need to take a closer look at what Sequel is doing in such cases, and figure out whether we want to have the same behavior or not.

**Comment by solnic** [comment]
One more thing - we're making this change as folks had specific problems with strict types, which means there were specific cases where it didn't work, so, let's start with spec examples covering these specific cases so that we know this change is fixing that for people. /cc @jodosha @cflipse

**Comment by flash-gordon** [comment]
@solnic OK, so it seems Sequel doesn't do anything special with values unless they are has special Sequel types, which is good fwiw. All coercions are made by DB-specific adapters, not by Sequel itself. Have a look at [the specs I wrote](https://github.com/rom-rb/rom-sql/pull/101/files#diff-8ce4d60fa4157c7143b75b2a0cb11762R97). I got a really weird behavior for SQLite under JRuby, it  inserts strings instead of timestamps I've no idea why this happens

**Comment by flash-gordon** [comment]
SQLite under JRuby writes data to the database as is, no coercions involved.

**Comment by flash-gordon** [comment]
Also, I want to stress that if a column has a default value and a not null constraint `nil` won't be ignored so that a resulting `INSERT` statement will try insert `NULL` i.e. violate the constraint. _I think_ it's alright/expected, wdyt? /cc @solnic @jodosha @cflipse

**Comment by cflipse** [comment]
Hey, sorry ... been a busy week.

So, if you're saying that if I try and insert a row with, say, `user_id: nil` and there's a not null constraint ... I'm totally okay with that erroring if I try to _set_ the column to null.

If it's an update, and the column isn't named in update parameters, than I wouldn't expect an error, but I'm pretty sure that's not what we're talking about here ... ;)

**Comment by cflipse** [comment]
aaand, I tried to check the branch locally against the project I had that was inspiring the original bug report, but ...

```
flip@meteu:~/src/get_ready_server (check-rom)$ be rspec
bundler: failed to load command: rspec (/home/flip/.gem/ruby/2.3.0/bin/rspec)
Bundler::GemRequireError: There was an error while trying to load the gem 'rom-sql'.
Gem Load Error is: undefined method `define' for nil:NilClass
Backtrace for gem load error is:
/home/flip/src/rom-rb/rom-support/lib/rom/support/options.rb:165:in `option'
/home/flip/src/rom-rb/rom-sql/lib/rom/sql/association/many_to_many.rb:9:in `<class:ManyToMany>'
/home/flip/src/rom-rb/rom-sql/lib/rom/sql/association/many_to_many.rb:4:in `<class:Association>'
/home/flip/src/rom-rb/rom-sql/lib/rom/sql/association/many_to_many.rb:3:in `<module:SQL>'
```

that using a GH based checkout of `rom`, `rom-support` and `rom-sql` .. I'm too tired to dig further on that right now.  on the one hand, I know that using the new updates is helpful and occasionally necessary.  On the other hand, it occasionally makes checking a bugfix branch like this a real pain.  :/

**Comment by solnic** [comment]
> Also, I want to stress that if a column has a default value and a not null constraint nil won't be ignored so that a resulting INSERT statement will try insert NULL i.e. violate the constraint. I think it's alright/expected, wdyt?

`nil` is a value, so if you pass in a nil, you pass a value, if a column has not-null constraint, it is expected that it will raise a constraint error. If somebody wants to rely on db-side default values, then nils should not be passed to commands.

**Pull request merged**
