### PR TITLE
[PG] Add ltree support

### PR DESCRIPTION
**Pull request by GustavoCaso**
#145 

Add support for `ltree`

@flash-gordon is my first time adding a new Type please comment as much as need it, I would apply the changes happily

### CODE REVIEW

**Comment by v-kolesnikov** [comment]
Hi, Gustavo!

How you fixed this problem: https://travis-ci.org/rom-rb/rom-sql/jobs/281666160 ?
I'm working on #160 and met same problem on JRuby builds.

**Comment by GustavoCaso** [comment]
Hi @v-kolesnikov.

I force coercion `to_s` at the implementation level https://github.com/rom-rb/rom-sql/blob/1b65d4666a7db82d8f6105c347b70f8d06a5da4a/lib/rom/sql/extensions/postgres/types/ltree.rb#L22

@flash-gordon pointed out to me.

**Comment by v-kolesnikov** [comment]
Thank you, @GustavoCaso. I will try to fix it in same way.

**Comment by flash-gordon** [comment]
I'm gonna leave it open until 2.0 is out

**Comment by solnic** [comment]
Closing in favor of #246

**Pull request closed without merging**
