### PR TITLE
Add Relation#read(sql_str)

### PR DESCRIPTION
**Pull request by solnic**
refs hanami/model#345
refs hanami/model#354

### CODE REVIEW

**Comment by solnic** [comment]
@flash-gordon so I did this, because it should be useful in general + hanami folks will benefit. Not entirely sure if the method name is good though

**Comment by flash-gordon** [comment]
JFYI, in Sequel it's called "fetch" (`#[]` == `#fetch`), in my opinion it's not a fortunate name either

**Comment by timriley** [comment]
`#read` actually seems pretty good to me. It feels analogous with reading a file, both in terms of potential cost and intended result.

**Comment by solnic** [comment]
@flash-gordon yeah both `#[]` and `#fetch` are very bad names. We actually already have `#fetch` that expects PK and returns a single tuple

**Comment by solnic** [comment]
FWIW in rom-yesql the same method (but in Dataset) is also [called read](https://github.com/rom-rb/rom-yesql/blob/master/lib/rom/yesql/dataset.rb#L22-L24). So let's just stick to it.

**Pull request merged**
