### PR TITLE
Move command timestamp plugin to rom-core

### PR DESCRIPTION
**Pull request by GustavoCaso**
This PR is part to fix https://github.com/rom-rb/rom/issues/467

This PR is part of one in `rom-core` https://github.com/rom-rb/rom/pull/469

### CODE REVIEW

**Comment by cflipse** [comment]
I might suggest leaving the specs in place, so we can verify that the version included in core behaves the same ...

**Comment by GustavoCaso** [comment]
Nice @cflipse. 

I did actually move all the test from `rom-sql` to `rom-core` https://github.com/rom-rb/rom/blob/b7db7febfb1aeb3c46f5a41cdecd1508373e4de9/core/spec/unit/rom/plugins/command/timestamps_spec.rb

**Comment by cflipse** [comment]
Oh, I figured you _did_ move the tests along with the code; I wasn't suggesting that you hadn't.

Rather, leave the specs in here _as well_ until after the next release, so they can act as a canary, to let us know if anything gets out of sync between releases.  After release, or maybe a minor release, they can be removed.

**Comment by GustavoCaso** [comment]
Thanks for the explanation @cflipse I will bring back the specs 😄

**Pull request merged**
