### PR TITLE
Add PG bytea type for binary data

### PR DESCRIPTION
**Pull request by flash-gordon**

### CODE REVIEW

**Comment by solnic** [comment]
the CI failed and it looks similar to what I've heard lately that latest sequel version doesn't set logger the way it used to so we end up with `nil` :/

**Comment by flash-gordon** [comment]
@solnic don't worry, I'll handle it 😎

**Comment by flash-gordon** [comment]
@solnic is it ready to be merged?

**Comment by solnic** [comment]
👍

**Pull request merged**
